-- V1__baseline_schema.sql
-- Baseline schema for the goaly application. Mirrors the schema produced by
-- the previous Hibernate `update` runs (validated against a live database)
-- and the `db/migration_manual.sql` / `db/fix_goal_schema.sql` scripts.

CREATE TABLE goals (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    unit               VARCHAR(255) NOT NULL,
    target_value       NUMERIC(38,2) NOT NULL,
    period             VARCHAR(255) NOT NULL,
    amount_per_period  NUMERIC(38,2) NOT NULL,
    is_active          BOOLEAN NOT NULL,
    description        VARCHAR(255),
    CONSTRAINT goals_period_check CHECK (period IN ('DAY','WEEK','WORKWEEK','WEEKEND','MONTH','YEAR'))
);

CREATE TABLE daily_entries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id        BIGINT NOT NULL,
    entry_date     DATE NOT NULL,
    actual_value   NUMERIC(38,2) NOT NULL,
    target_value   NUMERIC(38,2) NOT NULL,
    note           VARCHAR(1000)
);

CREATE TABLE target_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id     BIGINT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE,
    period      VARCHAR(255) NOT NULL,
    value       NUMERIC(38,2) NOT NULL,
    CONSTRAINT target_history_period_check CHECK (period IN ('DAY','WEEK','WORKWEEK','WEEKEND','MONTH','YEAR')),
    CONSTRAINT uk_target_history_goal_date UNIQUE (goal_id, valid_from)
);
